/**
 * Every user-facing sentence lives in this ONE file, so translating the app later (e.g. into Hindi)
 * means editing only this file. Plain English, no jargon.
 */
export const S = {
  appName: "Astrotalk Live",

  invalid: {
    title: "This link is not valid",
    body: "Please check the link you were sent, or ask the Astrotalk team for a new one.",
  },

  live: {
    hello: (name: string) => `Hello, ${name}`,
    noShifts: "You have no upcoming shifts",
    noShiftsHelp: "When the team schedules you, your next shift will appear here.",
    nextShift: "Your next shift",
    upcoming: "Upcoming shifts",
    startsIn: "Starts in",
    greenRoomOpens: (mins: number) => `Your green room opens ${mins} minutes before you go on air.`,
    testDevices: "Test your camera and microphone",
    testDevicesHelp: "This is only a preview on your own screen. Nothing is sent anywhere until you are on air.",
    turnOnDevices: "Turn on camera and microphone",
    camera: "Camera",
    microphone: "Microphone",
    micLevel: "Microphone level (speak to see it move)",
    framingGuide: "Viewers on Instagram see only the bright middle part",
    devicesDenied:
      "Your browser is blocking the camera or microphone. Click the camera icon next to the web address, choose Allow, then reload this page.",
    devicesMissing: "We could not find a camera or microphone. Please plug one in, then press the button again.",
    devicesError: "We could not start your camera or microphone. Close other apps that use them (Zoom, Meet, Teams) and try again.",
    networkCheck: "Check my internet",
    networkChecking: "Checking...",
    networkFailed: "We could not reach the server. Please check your internet and try again.",
    networkGood: "Your internet looks good.",
    networkOk: "Your internet is okay, but a wired connection would be safer.",
    networkPoor: "Your internet looks weak. Move closer to the router or use a cable.",
    greenRoomTitle: "You are ready",
    greenRoomBody: (time: string) => `You go on air at ${time}`,
    greenRoomHelp: "Stay on this page. You will go on air automatically. Nothing is being shown to viewers yet.",
    goingOnAir: "Going on air...",
    onAir: "ON AIR",
    timeLeft: "Time left",
    muteMic: "Mute microphone",
    unmuteMic: "Unmute microphone",
    cameraOff: "Turn camera off",
    cameraOn: "Turn camera on",
    micIsMuted: "Your microphone is muted. Viewers cannot hear you.",
    cameraIsOff: "Your camera is off. Viewers cannot see you.",
    warn: (mins: number) => (mins === 1 ? "1 minute left. Please wrap up." : `${mins} minutes left.`),
    overTitle: "Thank you, your shift is over",
    overBody: "Your camera and microphone have been switched off. You can close this page.",
    overNext: (when: string) => `Your next shift is ${when}.`,
    replacedTitle: "This page was opened somewhere else",
    replacedBody: "You opened your link on another tab or device, so this one has been disconnected. Only the newest one stays connected.",
    useThisOne: "Use this tab instead",
    removedTitle: "You were taken off the stage",
    removedBody: "The Astrotalk team ended your turn. Please contact them if this is a surprise.",
    connection: {
      connecting: "Connecting...",
      connected: "Connected",
      reconnecting: "Connection lost. Reconnecting...",
      disconnected: "Not connected",
    },
    quality: { excellent: "Excellent", good: "Good", poor: "Poor", lost: "Lost", unknown: "Checking" } as Record<string, string>,
    offline: "You seem to be offline. We will keep trying.",
    tipEchoTitle: "Watching the Instagram Live on another device?",
    tipEcho: "Mute that device or use headphones, otherwise your mic will pick up the echo.",
    tipSetupTitle: "For the best picture and sound",
    tipSetup: [
      "Use wired internet or strong Wi-Fi.",
      "Wear headphones.",
      "Face a window or a light, not away from it.",
      "Close other video apps (Zoom, Meet, Teams).",
      "Keep this page open and visible.",
    ],
    timeZoneNote: "All times are India time (IST).",
  },

  ops: {
    title: "Astrotalk Live — Ops",
    login: { title: "Team login", password: "Password", submit: "Log in", wrong: "That password is not right.", tooMany: "Too many tries. Please wait a few minutes.", error: "Something went wrong. Please try again." },
    nav: { dashboard: "Dashboard", schedule: "Schedule", logout: "Log out" },
    status: {
      worker: "Schedule worker",
      workerDown: "The schedule worker is not running. Nobody will be put on air or taken off air automatically. Ask your developer to start it (see README, Troubleshooting).",
      livekit: "Video server",
      livekitDown: "Cannot reach the LiveKit video server.",
      offline: "Lost connection to this app. Retrying...",
      ok: "Running",
    },
    now: { title: "On air now", nobody: "Nobody is on air", nobodyHelp: "The transition video is playing.", left: "left", removedNote: "Taken off the stage by ops for this shift." },
    next: { title: "Next up", none: "Nobody else is scheduled in the next 12 hours.", startsIn: "starts in" },
    greenRoom: { title: "Green room", none: "Nobody is waiting.", connected: "Connected", notConnected: "Not connected" },
    controls: {
      title: "Stage controls",
      transitionOn: "Transition video: ON",
      transitionOff: "Transition video: OFF",
      showTransition: "Show transition video",
      hideTransition: "Hide transition video",
      mute: "Mute on-air astrologer",
      unmute: "Unmute on-air astrologer",
      remove: "Remove astrologer from stage",
      skip: "Skip to next astrologer now",
      confirmRemove: "Take the current astrologer off the stage? They will be disconnected and the transition video will play until their slot would have ended.",
      confirmSkip: "End the current shift now and put the next astrologer on air immediately?",
      yes: "Yes, do it",
      cancel: "Cancel",
    },
    stream: {
      title: "Instagram stream",
      none: "Nothing is streaming.",
      serverUrl: "Server URL",
      serverUrlHelp: "Copy it from Instagram Live Producer.",
      streamKey: "Stream key",
      streamKeyHelp: "Single-use. It is used once, never saved, and this box is cleared when you press the button.",
      label: "Label (optional)",
      start: "Start stream",
      rotateTitle: "Rotate the stream key",
      rotateHelp: "Do this about every 4 hours, before Instagram ends the Live. The old stream keeps running while the new one starts.",
      rotateStart: "Start new stream (keep old running)",
      stop: "Stop stream",
      confirmStop: "Stop the stream? Instagram viewers will see the Live end.",
      steps: {
        title: "Switch to the new stream — follow these steps",
        s1: "In Instagram Live Producer, check that the preview is receiving video from the NEW stream.",
        s2: "Click “Show transition video” below, end the old live in Instagram, then click “Go Live” on the new one.",
        s3: "When the new Live is on, click “Confirm switch”. This stops the old stream. Then hide the transition video.",
      },
      confirmSwitch: "Confirm switch (stop the old stream)",
      status: { starting: "Starting", active: "Live", ending: "Ending", ended: "Ended", failed: "Failed" } as Record<string, string>,
      preview: "New stream (preview, not live yet)",
      age: "Stream age",
      rotateNow: "Rotate the stream key now (Instagram 4-hour limit)",
      alertTitle: "The stream stopped unexpectedly",
      restart: "Restart stream",
      restartNeedsKey: "For safety the old key is not kept. Paste a new key above and press Start.",
      dismiss: "Dismiss",
      notifications: "Alert me at 3h30 and 3h50",
      beep: "Play a beep",
      enableNotifications: "Allow browser notifications",
    },
    diag: { title: "Diagnostics" },
    events: { title: "Event log (latest 100)", none: "Nothing yet." },
  },

  schedule: {
    title: "Schedule",
    back: "Back to dashboard",
    thisWeek: "This week",
    prev: "Previous week",
    next: "Next week",
    coverage: (pct: number) => `Coverage for the next 7 days: ${pct}%`,
    gaps: (n: number) => (n === 1 ? "1 gap with nobody scheduled" : `${n} gaps with nobody scheduled`),
    noGaps: "No gaps",
    legendGap: "No astrologer scheduled",
    legendOverlap: "Overlap (must be fixed)",
    addShift: "Add shift",
    editShift: "Edit shift",
    astrologer: "Astrologer",
    date: "Date (IST)",
    start: "Starts (IST)",
    end: "Ends (IST)",
    endsNextDay: "This shift ends the next day.",
    save: "Save",
    delete: "Delete shift",
    confirmDeleteShift: "Delete this shift?",
    inactiveNote: "Switched off — will not go on air",
    astrologers: "Astrologers",
    addAstrologer: "Add astrologer",
    name: "Name",
    tagline: "Title (e.g. Vedic Astrologer)",
    photoUrl: "Photo address (optional, https://…)",
    copyLink: "Copy link",
    copyMessage: "Copy link message",
    copied: "Copied",
    regenerate: "New link",
    confirmRegenerate: "Create a new link for this astrologer? The old link stops working immediately and they will be disconnected if they are online. You must send them the new link.",
    deactivate: "Switch off",
    activate: "Switch on",
    edit: "Edit",
    inactive: "Switched off",
    templates: "Recurring slots",
    templatesHelp: "For example “Ravi, every day, 14:00 to 15:00”. The system creates the real shifts for the next 14 days, and keeps doing so.",
    addTemplate: "Add recurring slot",
    startTime: "Start time (IST, 24-hour)",
    length: "Length (minutes)",
    days: "Days",
    everyDay: "Every day",
    weekdays: "Mon–Fri",
    createNow: "Create shifts now",
    deleteTemplate: "Delete",
    confirmDeleteTemplate: "Delete this recurring slot?",
    alsoDeleteFuture: "Also delete its future shifts that have not started",
    import: "Import from CSV",
    importHelp: "One row per shift. New astrologers in the file are created automatically.",
    sample: "Download sample CSV",
    chooseFile: "Choose a CSV file",
    orPaste: "or paste the contents here",
    preview: "Check the file",
    doImport: "Import",
    whatsapp: (name: string, link: string) =>
      `Namaste ${name} 🙏\n\nThis is your personal Astrotalk Live link. Please do not share it:\n${link}\n\nHow it works:\n1. Open the link in Chrome on your laptop a few minutes before your slot.\n2. Allow camera and microphone and check your picture.\n3. Stay on the page: you go on air automatically at your slot time, and the page tells you when your time is over.\n\nTip: use headphones, and mute the Instagram Live if you watch it on another device.`,
  } as const,

  layout: {
    connecting: "Connecting...",
    nextUp: (name: string, time: string) => `Next: ${name} at ${time}`,
  },
} as const;
